#!/bin/bash

DEBUG=1

SSO_GATEKEEPER_ID=$1
SLN=lumada-data-flow-studio-$SSO_GATEKEEPER_ID

echo "SLN: $SLN"

BASE_URL=$2
DISCOVERY_URL=$BASE_URL/auth/realms/master
GATEKEEPER_SECRET="$SLN-sso-gatekeeper"
GATEKEEPER_YAML="$GATEKEEPER_SECRET.yaml"
JSON_DATA_PATH=".data.\"$GATEKEEPER_YAML\""

function tmpfile() {
    local tmp_filename=$SLN
    local tmpfile=$(mktemp /tmp/lcp-$tmp_filename.XXXX)
    exec 3>$tmpfile
    rm $tmpfile
    echo $tmpfile
}

function log() {
    [ -z "$DEBUG" ] && return 0
    echo $@
}

function log_file() {
    [ -z "$DEBUG" ] && return 0
    echo "-----------------"
    cat $SLN
    echo "-----------------"
    echo
}

TMP_DATA_SRC=$(tmpfile data-src)

echo "kubectl get secret $GATEKEEPER_SECRET -o json | jq -r "$JSON_DATA_PATH" | base64 -d >$TMP_DATA_SRC"

kubectl get secret $GATEKEEPER_SECRET -o json | jq -r "$JSON_DATA_PATH" | base64 -d >$TMP_DATA_SRC

log "Retrieved secret data:"
log_file $TMP_DATA_SRC

TMP_DATA_DEST=$(tmpfile data-dest)

cat $TMP_DATA_SRC | yq w - 'discovery-url' $DISCOVERY_URL >$TMP_DATA_DEST

log "Updated secret data to:"
log_file $TMP_DATA_DEST

TMP_PATCH_FILE=$(tmpfile secret-patch)

jq -nc --arg "$GATEKEEPER_YAML" "$(cat $TMP_DATA_DEST | base64)" '{"data" : $ARGS.named}' > $TMP_PATCH_FILE

log "Sending patch:"
log_file $TMP_PATCH_FILE

kubectl patch secret $GATEKEEPER_SECRET --type merge --patch "$(cat $TMP_PATCH_FILE)"